batch: 32
cache: true
data: data/processed/dataset.yaml
device: mps
epochs: 25
fraction: 1.0
imgsz: 416
lr0: 0.01
model: yolov8m.pt
momentum: 0.937
name: baseline
optimizer: SGD
project: outputs/checkpoints
save_period: 5
weight_decay: 0.0005
workers: 0
