augment: true
batch: 32
cache: true
cos_lr: true
data: data/processed/dataset.yaml
device: mps
epochs: 15
fraction: 1.0
imgsz: 416
lr0: 0.001
model: yolov8m.pt
momentum: 0.937
name: improved
optimizer: AdamW
project: outputs/checkpoints
save_period: 5
weight_decay: 0.0005
workers: 0
